name: Fear and Greed Alert

  on:
    schedule:
      - cron: '0 7 * * *' # Exécute tous les jours à 07:00 UTC (09:00 CEST)
      - cron: '0 13 * * *' # Exécute tous les jours à 13:00 UTC (15:00 CEST)

  jobs:
    run-alert:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12.7' # Utilise la version Python 3.12.7
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install requests
        - name: Run feargreedalert script
          env:
            BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
            CHAT_ID: ${{ secrets.CHAT_ID }}
            LOG_FILE: /tmp/feargreedalert.log # Chemin temporaire spécifique
          run: python feargreedalert.py
